services:
  # Сервис PostgreSQL
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  # Сервис Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Основной сервис Django
  backend:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis

  # Celery Worker
  celery_worker:
    build: .
    command: celery -A drf_project worker --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

  # Celery Beat
  celery_beat:
    build: .
    command: celery -A drf_project beat --loglevel=info
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data: