[tool.poetry]
name = "drf-project"
version = "0.1.0"
description = "DRF Project"
authors = ["kiril_tarasov <kirilltaras1792@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
django = "^5.0.2"
djangorestframework = "^3.14.0"
python-dotenv = "^1.0.0"
psycopg2-binary = "^2.9.9"
pillow = "^10.0.0"
django-filter = "^23.3"
djangorestframework-simplejwt = "^5.2.2"
coverage = "^7.3.2"
drf-yasg = "^1.21.7"
django-cors-headers = "^4.2.0"
stripe = "^7.0.0"
celery = "^5.3.1"
eventlet = "^0.33.3"
redis = "^4.6.0"

[tool.poetry.group.dev.dependencies]
black = "^23.11.0"
flake8 = "^6.1.0"
ruff = "^0.1.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
